Merge develop changes back to master (#10)
* ISSUE-36: Avoid using SHOW DATABASES for alive check

MySQL 8.0 somehow starts a transaction when SHOW DATABASES is called.
Inadvertantly starting a transaction prevents disabling LOG_BIN
using SET SQL_LOG_BIN=0. Change the Server.is_alive() function
to use SELECT 1 FROM DUAL instead.

* Use rsplit instead of split to get mysql session user and host

* Finish georgexsh/mysql-utilities commit# 7d4f198

 - Add INFORMATION_SCHEMA-based event schema object handling

* Update change log and tweak version

* Fix retrieving unicode fields from the server

I happened to have an accented character in a varchar field here that
made mysqldbexport choke with:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 10: ordinal not in range(128)

So we check if the value is a unicode string, and if so we encode it
back to a UTF-8 string.

Works for me(TM) but I didn't run any other test.

* 1) updating datetime format 2) add __next__()

* alternative import for LogParserError

* remove unnecessary character

* Autoincrement handling fixes

 - Add --skip-opt-autoinc option to compare with table options, but skip
   the AUTO_INCREMENT table option in the comparision

* Change build number

* Update .gitignore

 - add more python things
 - ignore build script files
 - ignore VSCode cruft

* Add --skip-partitioning option to mysqldbcompare

 - Added --skip-partitioning option to ignore differences in
   partitioning between server1 and server2
 - Corrected implementation of --skip-opt-autoinc and
   --skip-table-options
 - TODO: Need to add tests for --skip-partitioning option